services:
  postgres:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - student-vol:/usr/local/pgsql/data

volumes:
  student-vol:
    external: true